package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	gctx "gorgonia.org/gorgonia/internal/context"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/gorgonia/values"
	"gorgonia.org/tensor"
)

// addOp is the base op for elementwise addition.
type addOp[DT any, T values.Value[DT]] struct{ binop }

// String implements fmt.Stringer.
func (op addOp[DT, T]) String() string { return "+" }

// Do performs elementwise addition.
func (op addOp[DT, T]) Do(ctx context.Context, vs ...T) (retVal T, err error) {
	if err := gctx.Handle(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	b := vs[1]

	ctx2, task := trace.NewTask(ctx, op.String())

	e := getEngine(a, b)
	var adder tensor.Adder[DT, T]
	var ok bool
	if adder, ok = e.(tensor.Adder[DT, T]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, adder, errors.ThisFn())
	}

	ashp := a.Shape()
	bshp := b.Shape()
	expShape := getLargestShape(ashp, bshp)
	var fo tensor.Option
	if retVal, fo, err = handleFuncOpts[DT](e, a, expShape); err != nil {
		return retVal, err
	}

	switch {
	case ashp.IsScalarEquiv() && bshp.IsScalarEquiv():
		err = adder.Add(ctx2, a, b, retVal, fo.Incr)
	case ashp.IsScalarEquiv() && !bshp.IsScalarEquiv():
		err = adder.AddScalar(ctx2, b, a.Data()[0], retVal, true, fo.Incr)
	case !ashp.IsScalarEquiv() && bshp.IsScalarEquiv():
		err = adder.AddScalar(ctx2, a, b.Data()[0], retVal, false, fo.Incr)
	default:
		err = adder.Add(ctx2, a, b, retVal, fo.Incr)
	}

	task.End()
	return retVal, err
}

// PreallocDo performs elementwise addition but with a preallocated return value.
// PreallocDo allows add to implement ops.PreallocOp.
func (op addOp[DT, T]) PreallocDo(ctx context.Context, prealloc T, vs ...T) (retVal T, err error) {
	if err := gctx.Handle(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	b := vs[1]

	ctx2, task := trace.NewTask(ctx, op.String())

	e := getEngine(a, b)
	var adder tensor.Adder[DT, T]
	var ok bool
	if adder, ok = e.(tensor.Adder[DT, T]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, adder, errors.ThisFn())
	}

	ashp := a.Shape()
	bshp := b.Shape()
	expShape := getLargestShape(ashp, bshp)
	var fo tensor.Option
	if retVal, fo, err = handleFuncOpts[DT](e, a, expShape, tensor.WithReuse(prealloc)); err != nil {
		return retVal, err
	}

	switch {
	case ashp.IsScalarEquiv() && bshp.IsScalarEquiv():
		err = adder.Add(ctx2, a, b, retVal, fo.Incr)
	case ashp.IsScalarEquiv() && !bshp.IsScalarEquiv():
		err = adder.AddScalar(ctx2, b, a.Data()[0], retVal, true, fo.Incr)
	case !ashp.IsScalarEquiv() && bshp.IsScalarEquiv():
		err = adder.AddScalar(ctx2, a, b.Data()[0], retVal, false, fo.Incr)
	default:
		err = adder.Add(ctx2, a, b, retVal, fo.Incr)
	}

	task.End()
	return retVal, err
}

// addVV is a tensor-tensor elementwise addition.
type addVV[DT any, T values.Value[DT]] struct {
	addOp[DT, T]
	binopVV
}

// addVS is a tensor-scalar elementwise addition.
type addVS[DT any, T values.Value[DT]] struct {
	addOp[DT, T]
	binopVS
}

// String implements fmt.Stringer.
func (op addVS[DT, T]) String() string { return "+·" }

// addSV is a scalar-tensor elementwise addition.
type addSV[DT any, T values.Value[DT]] struct {
	addOp[DT, T]
	binopSV
}

// String implements fmt.Stringer.
func (op addSV[DT, T]) String() string { return "·+" }
