package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"gorgonia.org/gorgonia/internal"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/gorgonia/values"
	"gorgonia.org/tensor"
)

// divOp is the base op for elementwise division.
type divOp[DT any, T values.Value[DT]] struct{ binop }

// String implements fmt.Stringer.
func (op divOp[DT, T]) String() string { return "÷" }

func (op divOp[DT, T]) do(ctx context.Context, a, b, prealloc T) (retVal T, err error) {
	if err := internal.HandleCtx(ctx); err != nil {
		return retVal, err
	}

	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, ret, fo, err := tensor.PrepBasicBinOpCis[DT](a, b, tensor.WithReuse(prealloc))
	if err != nil {
		return retVal, err
	}
	toIncr := fo.Incr
	toBroadcast := fo.Broadcast
	retVal = ret.(T)

	basicarither, ok := e.(tensor.BasicArither[DT, T])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, basicarither, errors.ThisFn())
	}

	switch {
	case toBroadcast:
		err = basicarither.DivBroadcastable(ctx, a, b, retVal, newAPA, newAPB, toIncr)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = basicarither.Div(ctx2, a, b, retVal, toIncr)
	}
	return retVal, err
}

// Do performs elementwise division.
func (op divOp[DT, T]) Do(ctx context.Context, vs ...T) (retVal T, err error) {
	a := vs[0]
	b := vs[1]
	var prealloc T
	return op.do(ctx, a, b, prealloc)
}

// PreallocDo performs elementwise division but with a preallocated return value.
// PreallocDo allows div to implement ops.PreallocOp.
func (op divOp[DT, T]) PreallocDo(ctx context.Context, prealloc T, vs ...T) (retVal T, err error) {
	a := vs[0]
	b := vs[1]
	return op.do(ctx, a, b, prealloc)
}

// divVV is a tensor-tensor elementwise division.
type divVV[DT any, T values.Value[DT]] struct {
	divOp[DT, T]
	binopVV
}

// divVS is a tensor-scalar elementwise division.
type divVS[DT any, T values.Value[DT]] struct {
	divOp[DT, T]
	binopVS
}

// String implements fmt.Stringer.
func (op divVS[DT, T]) String() string { return "÷·" }

// divSV is a scalar-tensor elementwise division.
type divSV[DT any, T values.Value[DT]] struct {
	divOp[DT, T]
	binopSV
}

// String implements fmt.Stringer.
func (op divSV[DT, T]) String() string { return "·÷" }
