package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"github.com/chewxy/hm"
	gctx "gorgonia.org/gorgonia/internal/context"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/gorgonia/types"
	"gorgonia.org/gorgonia/values"
	"gorgonia.org/tensor"
)

// elNeOp is the base op for elementwise not-equal-to.
type elNeOp[DT any, T values.Value[DT]] struct {
	binop
	retSame bool
}

// String implements fmt.Stringer.
func (op elNeOp[DT, T]) String() string { return "≠" }

// Do performs elementwise not-equal-to.
func (op elNeOp[DT, T]) Do(ctx context.Context, vs ...T) (retVal T, err error) {
	if err := gctx.Handle(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	b := vs[1]

	// Do the actual operation
	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, retVal, fo, err := tensor.PrepBinOpTrans[DT](a, b)
	if err != nil {
		return retVal, err
	}

	asSame := fo.AsType == t.Dtype()
	toBroadcast := fo.Broadcast

	comparer, ok := e.(tensor.Comparer[DT, Basic[DT]])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, comparer, errors.ThisFn())
	}
	if fo.Incr {
		return retVal, errors.Errorf("Unable to perform Incr for elNe")
	}
	switch {
	case toBroadcast:
		err = comparer.elNeBroadcastable(ctx, a, b, retVal, asSame, newAPA, newAPB)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = comparer.elNe(ctx2, a, b, retVal, asSame)

	}
	return retVal, err
}

// PreallocDo performs elementwise not-equal-to but with a preallocated return value.
// PreallocDo allows elNe to implement ops.PreallocOp.
func (op elNeOp[DT, T]) PreallocDo(ctx context.Context, prealloc T, vs ...T) (retVal T, err error) {
	if err := gctx.Handle(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	b := vs[1]

	ctx2, task := trace.NewTask(ctx, op.String())
	defer task.End()

	e, newAPA, newAPB, retVal, fo, err := tensor.PrepBinOpTrans[DT](a, b, tensor.WithReuse(prealloc))
	if err != nil {
		return retVal, err
	}

	asSame := fo.AsType == t.Dtype()
	toBroadcast := fo.Broadcast

	comparer, ok := e.(tensor.Comparer[DT, Basic[DT]])
	if !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, comparer, errors.ThisFn())
	}
	if fo.Incr {
		return retVal, errors.Errorf("Unable to perform Incr for elNe")
	}
	switch {
	case toBroadcast:
		err = comparer.elNeBroadcastable(ctx, a, b, retVal, asSame, newAPA, newAPB)
	default:
		if err := checkCompatibleShape(a.Shape(), b.Shape()); err != nil {
			return retVal, err
		}
		err = comparer.elNe(ctx2, a, b, retVal, asSame)

	}
	return retVal, err
}                                                  // DiffWRT returns {false, false} for elNe
func (op elNeOp[DT, T]) DiffWRT(inputs int) []bool { return twofalses }

// elNeVV is a tensor-tensor elementwise not-equal-to.
type elNeVV[DT any, T values.Value[DT]] struct {
	elNeOp[DT, T]
	binopVV
}

// Type returns the type: (·) : a → a → a or (·) :  a → a → b
func (op elNeVV[DT, T]) Type() hm.Type {
	a := hm.TypeVariable('a') // (T U) or U
	if op.retSame {
		return types.NewFunc(a, a, a)
	}
	b := types.MakeDependent(a, tensor.Bool) // (T Bool) or Bool
	return types.NewFunc(a, a, b)
}

// elNeVS is a tensor-scalar elementwise not-equal-to.
type elNeVS[DT any, T values.Value[DT]] struct {
	elNeOp[DT, T]
	binopVS
}

// String implements fmt.Stringer.
func (op elNeVS[DT, T]) String() string { return "≠·" }

// Type returns the type: (·) : a → b → a or (·) :  a → b → c
func (op elNeVS) Type() hm.Type {
	a := hm.TypeVariable('a') // (T U) or U
	b := hm.TypeVariable('b') // U
	if op.retSame {
		return types.NewFunc(a, b, a)
	}
	c := types.MakeDependent(a, tensor.Bool) // (T Bool) or Bool
	return types.NewFunc(a, b, c)
}

// elNeSV is a scalar-tensor elementwise not-equal-to.
type elNeSV[DT any, T values.Value[DT]] struct {
	elNeOp[DT, T]
	binopSV
}

// String implements fmt.Stringer.
func (op elNeSV[DT, T]) String() string { return "·≠" }

// Type returns the type: (·) : a → b → b or (·) :  a → b → c
func (op elNeSV[DT, T]) Type() hm.Type {
	a := hm.TypeVariable('a') // U
	b := hm.TypeVariable('b') // (T U) or U
	if op.retSame {
		return types.NewFunc(a, b, b)
	}
	c := types.MakeDependent(b, tensor.Bool) // (T Bool) or Bool
	return types.NewFunc(a, b, c)
}
