package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	"github.com/chewxy/hm"
	gctx "gorgonia.org/gorgonia/internal/context"
	"gorgonia.org/gorgonia/types"
	"gorgonia.org/gorgonia/values"
	"gorgonia.org/tensor"
)

// gteOp is the base op for elementwise greater-than-or-equal-to.
type gteOp struct {
	binop
	retSame bool
}

// String implements fmt.Stringer.
func (op gteOp) String() string { return "≥" }

// Do performs elementwise greater-than-or-equal-to.
func (op gteOp) Do(ctx context.Context, vs ...values.Value) (retVal values.Value, err error) {
	if err := gctx.Handle(ctx); err != nil {
		return nil, err
	}

	a := vs[0].(tensor.Tensor)
	b := vs[1].(tensor.Tensor)

	// Do the actual operation
	ctx2, task := trace.NewTask(ctx, op.String())
	if op.retSame {
		retVal, err = tensor.Gte(a, b, tensor.WithContext(ctx2), tensor.AsSameType())
	} else {
		retVal, err = tensor.Gte(a, b, tensor.WithContext(ctx2))
	}
	task.End()
	return retVal, err
}

// PreallocDo performs elementwise greater-than-or-equal-to but with a preallocated return value.
// PreallocDo allows gte to implement ops.PreallocOp.
func (op gteOp) PreallocDo(ctx context.Context, prealloc values.Value, vs ...values.Value) (retVal values.Value, err error) {
	if err := gctx.Handle(ctx); err != nil {
		return nil, err
	}

	a := vs[0].(tensor.Tensor)
	b := vs[1].(tensor.Tensor)

	ctx2, task := trace.NewTask(ctx, op.String())
	if op.retSame {
		retVal, err = tensor.Gte(a, b, tensor.WithReuse(prealloc), tensor.WithContext(ctx2), tensor.AsSameType())
	} else {
		retVal, err = tensor.Gte(a, b, tensor.WithReuse(prealloc), tensor.WithContext(ctx2))
	}
	task.End()
	return retVal, err
}                                          // DiffWRT returns {false, false} for gte
func (op gteOp) DiffWRT(inputs int) []bool { return twofalses }

// gteVV is a tensor-tensor elementwise greater-than-or-equal-to.
type gteVV struct {
	gteOp
	binopVV
}

// Type returns the type: (·) : a → a → a or (·) :  a → a → b
func (op gteVV) Type() hm.Type {
	a := hm.TypeVariable('a') // (T U) or U
	if op.retSame {
		return hm.NewFnType(a, a, a)
	}
	b := types.MakeDependent(a, tensor.Bool) // (T Bool) or Bool
	return hm.NewFnType(a, a, b)
}

// gteVS is a tensor-scalar elementwise greater-than-or-equal-to.
type gteVS struct {
	gteOp
	binopVS
}

// String implements fmt.Stringer.
func (op gteVS) String() string { return "≥·" }

// Type returns the type: (·) : a → b → a or (·) :  a → b → c
func (op gteVS) Type() hm.Type {
	a := hm.TypeVariable('a') // (T U) or U
	b := hm.TypeVariable('b') // U
	if op.retSame {
		return hm.NewFnType(a, b, a)
	}
	c := types.MakeDependent(a, tensor.Bool) // (T Bool) or Bool
	return hm.NewFnType(a, b, c)
}

// gteSV is a scalar-tensor elementwise greater-than-or-equal-to.
type gteSV struct {
	gteOp
	binopSV
}

// String implements fmt.Stringer.
func (op gteSV) String() string { return "·≥" }

// Type returns the type: (·) : a → b → b or (·) :  a → b → c
func (op gteSV) Type() hm.Type {
	a := hm.TypeVariable('a') // U
	b := hm.TypeVariable('b') // (T U) or U
	if op.retSame {
		return hm.NewFnType(a, b, b)
	}
	c := types.MakeDependent(b, tensor.Bool) // (T Bool) or Bool
	return hm.NewFnType(a, b, c)
}
