package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	gctx "gorgonia.org/gorgonia/internal/context"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/gorgonia/values"
	"gorgonia.org/tensor"
)

// powOp is the base op for elementwise exponentiation.
type powOp[DT any, T values.Value[DT]] struct{ binop }

// String implements fmt.Stringer.
func (op powOp[DT, T]) String() string { return "^" }

// Do performs elementwise exponentiation.
func (op powOp[DT, T]) Do(ctx context.Context, vs ...T) (retVal T, err error) {
	if err := gctx.Handle(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	b := vs[1]

	ctx2, task := trace.NewTask(ctx, op.String())

	e := getEngine(a, b)
	var arither tensor.Arither[DT, T]
	var ok bool
	if arither, ok = e.(tensor.Arither[DT, T]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, arither, errors.ThisFn())
	}

	ashp := a.Shape()
	bshp := b.Shape()
	expShape := getLargestShape(ashp, bshp)
	var fo tensor.Option
	if retVal, fo, err = handleFuncOpts[DT](e, a, expShape); err != nil {
		return retVal, err
	}

	switch {
	case ashp.IsScalarEquiv() && bshp.IsScalarEquiv():
		err = arither.Pow(ctx2, a, b, retVal, fo.Incr)
	case ashp.IsScalarEquiv() && !bshp.IsScalarEquiv():
		err = arither.PowScalar(ctx2, b, a.Data()[0], retVal, true, fo.Incr)
	case !ashp.IsScalarEquiv() && bshp.IsScalarEquiv():
		err = arither.PowScalar(ctx2, a, b.Data()[0], retVal, false, fo.Incr)
	default:
		err = arither.Pow(ctx2, a, b, retVal, fo.Incr)
	}

	task.End()
	return retVal, err
}

// PreallocDo performs elementwise exponentiation but with a preallocated return value.
// PreallocDo allows pow to implement ops.PreallocOp.
func (op powOp[DT, T]) PreallocDo(ctx context.Context, prealloc T, vs ...T) (retVal T, err error) {
	if err := gctx.Handle(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	b := vs[1]

	ctx2, task := trace.NewTask(ctx, op.String())

	e := getEngine(a, b)
	var arither tensor.Arither[DT, T]
	var ok bool
	if arither, ok = e.(tensor.Arither[DT, T]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, arither, errors.ThisFn())
	}

	ashp := a.Shape()
	bshp := b.Shape()
	expShape := getLargestShape(ashp, bshp)
	var fo tensor.Option
	if retVal, fo, err = handleFuncOpts[DT](e, a, expShape, tensor.WithReuse(prealloc)); err != nil {
		return retVal, err
	}

	switch {
	case ashp.IsScalarEquiv() && bshp.IsScalarEquiv():
		err = arither.Pow(ctx2, a, b, retVal, fo.Incr)
	case ashp.IsScalarEquiv() && !bshp.IsScalarEquiv():
		err = arither.PowScalar(ctx2, b, a.Data()[0], retVal, true, fo.Incr)
	case !ashp.IsScalarEquiv() && bshp.IsScalarEquiv():
		err = arither.PowScalar(ctx2, a, b.Data()[0], retVal, false, fo.Incr)
	default:
		err = arither.Pow(ctx2, a, b, retVal, fo.Incr)
	}

	task.End()
	return retVal, err
}

// powVV is a tensor-tensor elementwise exponentiation.
type powVV[DT any, T values.Value[DT]] struct {
	powOp[DT, T]
	binopVV
}

// powVS is a tensor-scalar elementwise exponentiation.
type powVS[DT any, T values.Value[DT]] struct {
	powOp[DT, T]
	binopVS
}

// String implements fmt.Stringer.
func (op powVS[DT, T]) String() string { return "^·" }

// powSV is a scalar-tensor elementwise exponentiation.
type powSV[DT any, T values.Value[DT]] struct {
	powOp[DT, T]
	binopSV
}

// String implements fmt.Stringer.
func (op powSV[DT, T]) String() string { return "·^" }
