package stdops

// Code generated by genops, which is a ops generation tool for Gorgonia. DO NOT EDIT.

import (
	"context"
	"runtime/trace"

	gctx "gorgonia.org/gorgonia/internal/context"
	"gorgonia.org/gorgonia/internal/errors"
	"gorgonia.org/gorgonia/values"
	"gorgonia.org/tensor"
)

// subOp is the base op for elementwise subtraction.
type subOp[DT any, T values.Value[DT]] struct{ binop }

// String implements fmt.Stringer.
func (op subOp[DT, T]) String() string { return "-" }

// Do performs elementwise subtraction.
func (op subOp[DT, T]) Do(ctx context.Context, vs ...T) (retVal T, err error) {
	if err := gctx.Handle(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	b := vs[1]

	ctx2, task := trace.NewTask(ctx, op.String())

	e := getEngine(a, b)
	var basicarither tensor.BasicArither[DT, T]
	var ok bool
	if basicarither, ok = e.(tensor.BasicArither[DT, T]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, basicarither, errors.ThisFn())
	}

	ashp := a.Shape()
	bshp := b.Shape()
	expShape := getLargestShape(ashp, bshp)
	var fo tensor.Option
	if retVal, fo, err = handleFuncOpts[DT](e, a, expShape); err != nil {
		return retVal, err
	}

	switch {
	case ashp.IsScalarEquiv() && bshp.IsScalarEquiv():
		err = basicarither.Sub(ctx2, a, b, retVal, fo.Incr)
	case ashp.IsScalarEquiv() && !bshp.IsScalarEquiv():
		err = basicarither.SubScalar(ctx2, b, a.Data()[0], retVal, true, fo.Incr)
	case !ashp.IsScalarEquiv() && bshp.IsScalarEquiv():
		err = basicarither.SubScalar(ctx2, a, b.Data()[0], retVal, false, fo.Incr)
	default:
		err = basicarither.Sub(ctx2, a, b, retVal, fo.Incr)
	}

	task.End()
	return retVal, err
}

// PreallocDo performs elementwise subtraction but with a preallocated return value.
// PreallocDo allows sub to implement ops.PreallocOp.
func (op subOp[DT, T]) PreallocDo(ctx context.Context, prealloc T, vs ...T) (retVal T, err error) {
	if err := gctx.Handle(ctx); err != nil {
		return retVal, err
	}

	a := vs[0]
	b := vs[1]

	ctx2, task := trace.NewTask(ctx, op.String())

	e := getEngine(a, b)
	var basicarither tensor.BasicArither[DT, T]
	var ok bool
	if basicarither, ok = e.(tensor.BasicArither[DT, T]); !ok {
		return retVal, errors.Errorf(errors.EngineSupport, e, basicarither, errors.ThisFn())
	}

	ashp := a.Shape()
	bshp := b.Shape()
	expShape := getLargestShape(ashp, bshp)
	var fo tensor.Option
	if retVal, fo, err = handleFuncOpts[DT](e, a, expShape, tensor.WithReuse(prealloc)); err != nil {
		return retVal, err
	}

	switch {
	case ashp.IsScalarEquiv() && bshp.IsScalarEquiv():
		err = basicarither.Sub(ctx2, a, b, retVal, fo.Incr)
	case ashp.IsScalarEquiv() && !bshp.IsScalarEquiv():
		err = basicarither.SubScalar(ctx2, b, a.Data()[0], retVal, true, fo.Incr)
	case !ashp.IsScalarEquiv() && bshp.IsScalarEquiv():
		err = basicarither.SubScalar(ctx2, a, b.Data()[0], retVal, false, fo.Incr)
	default:
		err = basicarither.Sub(ctx2, a, b, retVal, fo.Incr)
	}

	task.End()
	return retVal, err
}

// subVV is a tensor-tensor elementwise subtraction.
type subVV[DT any, T values.Value[DT]] struct {
	subOp[DT, T]
	binopVV
}

// subVS is a tensor-scalar elementwise subtraction.
type subVS[DT any, T values.Value[DT]] struct {
	subOp[DT, T]
	binopVS
}

// String implements fmt.Stringer.
func (op subVS[DT, T]) String() string { return "-·" }

// subSV is a scalar-tensor elementwise subtraction.
type subSV[DT any, T values.Value[DT]] struct {
	subOp[DT, T]
	binopSV
}

// String implements fmt.Stringer.
func (op subSV[DT, T]) String() string { return "·-" }
