@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/go.puml
!include DEVICONS/java.puml
!include DEVICONS/redis.puml
!include DEVICONS/google.puml
!include DEVICONS/facebook.puml
!include FONTAWESOME/users.puml

sprite $logo48 [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF5870FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF98888888FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF988888888889FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF9888788888878988FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF989988888888889989FFFFFFFFFFFFFFF
FFFFFFFFFFFFF9999999999998999999999FFFFFFFFFFFFF
FFFFFFFFFFF8999999999999999999999999BFFFFFFFFFFF
FFFFFFFFF9959A9999999999999999999999899FFFFFFFFF
FFFFFFFFB999999999999999999999999999999BFFFFFFFF
FFFFFFFF99999999999999999999999999999999FFFFFFFF
FFFFFFFF999999999999999999999999999999A9FFFFFFFF
FFFFFFFF99999999999999999999999999999999FFFFFFFF
FFFFFFFF99999999999999999999999999999999FFFFFFFF
FFFFFFFFAAAA9AAA9999999AA9999999AAAAAAAAFFFFFFFF
FFFFFFFFAAAAAAAAAA999AFFFFA9999AAAAAAAAAFFFFFFFF
FFFFFFFFAAAAAAAAAAA9AFFFFFFC999AAAAAAAAAFFFFFFFF
FFFFFFFFAAAAAAAAAAAFFFBABCBFFAAAAAAAAAAAFFFFFFFF
FFFFFFFFAAAAAAAAAAAFFFAAAAAAFFFAAAAAAAAAFFFFFFFF
FFFFFFFFAAAAAAAAAAAFFFAAAAAAABFFFAAAAACAFFFFFFFF
FFFFFFFFAAAAAAAAAAAFFFAAAAAAAAABFF9AAAAAFFFFFFFF
FFFFFFFFAAAAAAAAAAAFFFAAAAAAABBBBFFFFFFFFFFFFFFF
FFFFFFFFBBBBABBBAAAFFFAABBBBBBBBBBBFFFFFFFFFFFFF
FFFFFFFFBBBBBBBBBBBFFFBBBBBBBBBBBBBBCFFFFFFFFFFF
FFFFFFFFBBBBBBBBBBBFFFBBBBBBBBBBBBABBBCFFFFFFFFF
FFFFFFFFBBBBBBBBBBBFFFBBBBBBBBBBBBBBBBBEFFFFFFFF
FFFFFFFFBBBBBBBBBBBFFFBBBBBBBBBBBBBBBBBBFFFFFFFF
FFFFFFFFBBBBBBBBBBBFFFBBBBBBBBBBBBBBBBBBFFFFFFFF
FFFFFFFFBBBBBBBBBBBFFFBBBBBBBBBBBBBBBBBBFFFFFFFF
FFFFFFFFBBBBBBBBBBBCFFBBBBCBBBBBBBBBBBBBFFFFFFFF
FFFFFFFFCBCCCCCCBBCBCFFFDBBBBBBCCCCCCCBBFFFFFFFF
FFFFFFFFCCCCCCCCCCCCCCCFFCCCCCCCCCCCCCCCFFFFFFFF
FFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFF
FFFFFFFFCCCCCCCCCCCCCCFCCECCCCCCCCCCCCCCFFFFFFFF
FFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFF
FFFFFFFFDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDFFFFFFFF
FFFFFFFFCBCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCFFFFFFFF
FFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFF
FFFFFFFFFFCCCCCCCCDDDDDDDDDDDDCCCCCCCCFFFFFFFFFF
FFFFFFFFFFFFDCCC2DDDDDDDDDDDDDDFCCCDFFFFFFFFFFFF
FFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFEDDDDDDDDDDDDEFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFDDDDEEDDDDFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFDDDDDDFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}


' LAYOUT_WITH_LEGEND()
Person(application_dev,"Application Developer")
Container_Boundary(goapp,"Go Application","go") {
    Component(main,"main","package main", "Main routine, to deal with I/O etc.", "go")
    Component(ml,"ML Engine",)
}

Alice -> Bob : Testing <$logo48>

@enduml