on: 
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
name: Code Coverage
jobs:
  coverage:
    runs-on: "ubuntu-latest"
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Calc coverage
      run: |
        ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=$(go env GOVERSION | sed 's/\.[0-9]*$//') go test -v -covermode=atomic -coverprofile=coverage.out
    - uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: coverage.out
        flags: unittests # optional
        name: codecov-gorgonia # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
